---
driver:
  name: ec2
  aws_ssh_key_id: yolo
  region: us-east-1
  availability_zone: us-east-1b

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: amazon
    driver:
      image_id: ami-26ebbc5c
    transport:
        username: ec2-user
        ssh_key: /opt/yolo.pem


suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
